resource_group_name = "myResourceGroup"
location            = "East US"
vnet_name           = "myVnet"
subnet_name         = "mySubnet"
nsg_name            = "myNSG"
route_table_name    = "myRouteTable"
address_space       = ["10.0.0.0/16"]
subnet_address_prefix = ["10.0.1.0/24"]
nsg_rule_name       = "myNSGRule"
